name: Singularity Build (via docker)
on:
    push:
        branches:
            - master
        paths:
            - "*.def"
jobs:
    build:
        name: Build
        runs-on: ubuntu-20.04
        container:
            image: quay.io/singularity/singularity:v3.7.1
            options: --privileged
        steps:
            - name: Check out code for the container build
              uses: actions/checkout@v2

            - name: Build Treep Container
              continue-on-error: true
              run: sudo -E singularity build treep.sif treep.def

            - name: Build Black Container
              continue-on-error: true
              run: sudo -E singularity build black.sif black.def
